import type { Metric } from "@/types/metric";

export const MOCK_METRICS: Metric[] = [
  {
    id: "metric-1",
    name: "Demographic Parity",
    category: "Fairness",
    status: "active",
    description:
      "Measures whether positive prediction rates are consistent across demographic groups in classification systems.",
    aiSystemTypes: ["Classification", "Recommendation"],
    dataSource: "API endpoint",
    frequency: "Daily",
    threshold: { operator: "gt", minimum: 0.85, target: 0.92, unit: "ratio" },
    owner: "Sarah Chen",
    alerts: {
      recipients: ["sarah.chen@example.com", "fairness-team@example.com"],
      conditions: ["Below minimum threshold", "Approaching minimum threshold"],
      escalation: "Notify compliance team",
    },
    createdAt: "2025-11-01T09:00:00.000Z",
    updatedAt: "2026-01-15T14:30:00.000Z",
  },
  {
    id: "metric-2",
    name: "Model Explainability Score",
    category: "Transparency",
    status: "active",
    description:
      "Composite score reflecting the availability and quality of model explanations for end-user decisions.",
    aiSystemTypes: ["Classification", "NLP", "Generative AI"],
    dataSource: "SDK integration",
    frequency: "Weekly",
    threshold: { operator: "gt", minimum: 0.7, target: 0.85, unit: "score" },
    owner: "James Okafor",
    alerts: {
      recipients: ["j.okafor@example.com"],
      conditions: ["Below minimum threshold", "Data unavailable"],
      escalation: "Notify manager",
    },
    createdAt: "2025-10-12T11:20:00.000Z",
    updatedAt: "2026-02-01T08:45:00.000Z",
  },
  {
    id: "metric-3",
    name: "Adversarial Robustness Index",
    category: "Robustness",
    status: "draft",
    description:
      "Evaluates model resilience against adversarial inputs across vision and NLP pipelines.",
    aiSystemTypes: ["Computer Vision", "NLP"],
    dataSource: "Manual upload",
    frequency: "Monthly",
    threshold: { operator: "gt", minimum: 0.9, target: 0.95, unit: "index" },
    owner: "Priya Sharma",
    alerts: {
      recipients: ["priya.sharma@example.com"],
      conditions: ["Below minimum threshold"],
      escalation: "None",
    },
    createdAt: "2026-03-01T16:00:00.000Z",
    updatedAt: "2026-03-10T10:15:00.000Z",
  },
  {
    id: "metric-4",
    name: "PII Exposure Rate",
    category: "Privacy",
    status: "active",
    description:
      "Tracks the rate at which personally identifiable information is exposed in model outputs.",
    aiSystemTypes: ["NLP", "Generative AI"],
    dataSource: "Database query",
    frequency: "Real-time",
    threshold: { operator: "lt", minimum: 0.01, target: 0.005, unit: "rate" },
    owner: "David Bates",
    alerts: {
      recipients: ["david.bates@example.com", "privacy-office@example.com"],
      conditions: [
        "Below minimum threshold",
        "Data unavailable",
        "Configuration change",
      ],
      escalation: "Block deployment",
    },
    createdAt: "2025-09-05T07:30:00.000Z",
    updatedAt: "2026-02-20T13:00:00.000Z",
  },
  {
    id: "metric-5",
    name: "Decision Audit Trail Coverage",
    category: "Accountability",
    status: "archived",
    description:
      "Percentage of automated decisions with a complete, immutable audit trail for regulatory review.",
    aiSystemTypes: ["Classification", "Recommendation"],
    dataSource: "Database query",
    frequency: "Daily",
    threshold: {
      operator: "gt",
      minimum: 0.95,
      target: 0.99,
      unit: "coverage",
    },
    owner: "Nishil Patel",
    alerts: {
      recipients: ["nishil.patel@example.com"],
      conditions: ["Below minimum threshold"],
      escalation: "Notify compliance team",
    },
    createdAt: "2025-06-18T12:00:00.000Z",
    updatedAt: "2025-12-01T09:00:00.000Z",
  },
  {
    id: "metric-6",
    name: "Hallucination Rate",
    category: "Safety",
    status: "active",
    description:
      "Measures the frequency of factually incorrect or unsupported claims in generative AI outputs.",
    aiSystemTypes: ["Generative AI", "NLP"],
    dataSource: "API endpoint",
    frequency: "Daily",
    threshold: { operator: "lt", minimum: 0.05, target: 0.02, unit: "rate" },
    owner: "Gaurav Malhotra",
    alerts: {
      recipients: ["gaurav.malhotra@example.com", "safety-team@example.com"],
      conditions: [
        "Below minimum threshold",
        "Approaching minimum threshold",
        "Data unavailable",
      ],
      escalation: "Notify manager",
    },
    createdAt: "2025-11-20T15:45:00.000Z",
    updatedAt: "2026-03-05T11:30:00.000Z",
  },
];
